version: '3'

services:
  proxy:
    build: proxy
    container_name: proxy
    restart: unless-stopped
    volumes:
      - $PWD/letsencrypt:/etc/letsencrypt:rw
    env_file:
      - env
    ports:
      - 80:80
      - 443:443

  rancher:
    image: rancher/rancher
    container_name: rancher
    restart: unless-stopped
    volumes:
      - rancher-data:/var/lib/rancher

volumes:
  rancher-data:
